### ISSUE TITLE
How to use my own custom dataset. Is there any method to create custom dataset besides the existing NTU and kinetics skeletal dataset?

### ISSUE THREAD

**Issue by lakpa-tamang9** [opendr-eu/opendr#294]
https://github.com/opendr-eu/opendr/blob/28c53725285cb5f156aa785164c0a0ba9ce76b96/projects/perception/skeleton_based_action_recognition/benchmark/benchmark_stgcn.py#L38

**Comment by negarhdr** [comment]
Hi, Thanks for your interest in our tool. 

In order to train the models on a custom-skeleton dataset, you need first to employ lightweight openpose method to extract body poses from the videos. We have a code for that in this directory:
opendr/projects/perception/skeleton_based_action_recognition/demos/skeleton_extraction.py

Our models and learners are designed for NTU and kinetics-skeleton datasets. Therefore, after extracting body skeletons you need to do some preprocessing as well to meet the model's requirements.

The models receive a sequence of 300 skeletons for each sample. Therefore, if you have less than 300 frames in each video, you need to do padding to fulfill this. Also, we assumed that in each frame we have two skeletons (because NTU-RGBD and Kinetics datasets had some actions taken place by two-person interaction like "shaking hand"). So you need to check each frame and in case there are less than 2 skeletons in each frame, you need padding and if there are more than 2 skeletons in each frame you need to choose 2 of them (this is included in the code).

So the first step to prepare a custom dataset is to follow the preprocessing steps to make sure each input video will be modeled as a tensor of size CxTxV (2x300x18).
Please check out my codes in this directory and if you have further questions, we can discuss:

https://github.com/opendr-eu/opendr/tree/d3beb3b56fddb5f82e8b62ae5b4678e7f09a5f33/projects/perception/skeleton_based_action_recognition/demos

After preparing your custom data, you can just modify `args.dataset_name == 'nturgbd_cv'` for your own dataset.
